from __future__ import annotations

from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter(tags=["ui"])

UI_HTML = """<!doctype html>
<html lang="es">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>ShearTors RC - UI</title>
  <style>
    :root{--bg:#f3f7fc;--panel:#fff;--line:#cdd8e6;--txt:#16253a;--muted:#5d6f88;--accent:#0f5f79;--accent2:#0b4d62;--err:#a12821}
    *{box-sizing:border-box} body{margin:0;font-family:"IBM Plex Sans","Segoe UI",Tahoma,sans-serif;color:var(--txt);background:linear-gradient(150deg,#e9eff8 0%,var(--bg) 55%,#f7f9fd 100%)}
    .page{max-width:1160px;margin:0 auto;padding:20px 14px 30px}.title{margin:0;font-size:1.42rem}.subtitle{margin:6px 0 14px;color:var(--muted);font-size:.9rem}
    .layout{display:grid;grid-template-columns:minmax(0,1fr) 330px;gap:12px;align-items:start}
    .card{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:14px}.card+.card{margin-top:10px}
    .h2{margin:0 0 6px;font-size:1rem;font-weight:640}.note{margin:0 0 10px;color:var(--muted);font-size:.82rem}
    .grid{display:grid;gap:10px}.g3{grid-template-columns:repeat(3,minmax(0,1fr))}.g2{grid-template-columns:repeat(2,minmax(0,1fr))}
    .field label{display:block;margin-bottom:4px;font-size:.82rem;font-weight:620}.field input,.field select{width:100%;border:1px solid #bfccde;border-radius:8px;padding:9px 10px;font-size:.9rem;background:#fff}
    .field input:focus,.field select:focus{outline:none;border-color:var(--accent);box-shadow:0 0 0 3px rgba(15,95,121,.15)}
    .help{margin:5px 0 0;color:var(--muted);font-size:.76rem}.field [aria-invalid="true"]{border-color:var(--err);background:#fff8f8}
    .field-error{margin:5px 0 0;color:var(--err);font-size:.78rem}
    details.adv{border:1px solid var(--line);border-radius:10px;background:#f8fbff} details.adv>summary{list-style:none;cursor:pointer;padding:10px 11px;font-size:.88rem;font-weight:630}
    details.adv>summary::-webkit-details-marker{display:none} details.adv[open]>summary{border-bottom:1px solid var(--line)} .adv-body{padding:11px}
    .adv-block+.adv-block{margin-top:11px}.adv-block{border:1px solid #d3deec;border-radius:10px;padding:11px;background:#fff}
    .toggle{display:flex;align-items:center;gap:8px;margin-bottom:7px}.toggle input{width:16px;height:16px}.toggle label{font-size:.86rem;font-weight:630}
    .mini-note{margin:0 0 8px;color:var(--muted);font-size:.76rem}.adv-disabled{opacity:.62}.pairs{display:grid;gap:8px}.pair-row{display:grid;gap:8px;grid-template-columns:1fr 1fr 1fr auto;align-items:end}
    .mini-btn{border:1px solid #c8d5e8;border-radius:8px;padding:7px 10px;background:#eef3fa;font-size:.8rem;font-weight:620;cursor:pointer}.mini-btn-danger{border-color:#e3b7b3;background:#fff2f1;color:#8f2b25}.mini-btn:disabled{opacity:.68;cursor:not-allowed}
    .actions{display:flex;flex-wrap:wrap;gap:8px}.btn{min-width:180px;border-radius:9px;border:1px solid transparent;padding:10px 13px;cursor:pointer;font-size:.9rem;font-weight:640;display:inline-flex;align-items:center;justify-content:center;gap:7px}
    .btn-primary{color:#fff;background:linear-gradient(180deg,var(--accent),var(--accent2))}.btn-secondary{color:#1f3248;border-color:#c6d2e4;background:#e8edf6}.btn:disabled{opacity:.72;cursor:not-allowed}
    .spinner{width:12px;height:12px;border-radius:50%;border:2px solid rgba(255,255,255,.45);border-top-color:#fff;animation:spin .8s linear infinite;display:none}.btn.is-loading .spinner{display:inline-block}@keyframes spin{to{transform:rotate(360deg)}}
    .side{position:sticky;top:12px}.status{display:inline-flex;align-items:center;min-height:34px;border-radius:999px;border:1px solid #c8d5e6;background:#f2f6fb;color:#2a3e56;font-size:.84rem;font-weight:620;padding:7px 12px}
    .status.running{border-color:#d8be88;background:#fff8ea;color:#8c5a00}.status.ok{border-color:#abd3be;background:#ecf8f1;color:#1f6b43}.status.err{border-color:#e3b0ab;background:#fff1f0;color:var(--err)}
    .alert{margin-top:10px;border:1px solid #e4b5b1;background:#fdeceb;border-radius:9px;color:#5f1d1b;padding:9px 10px}.alert h4{margin:0;font-size:.86rem}.alert p{margin:4px 0 0;font-size:.76rem}.alert ul{margin:7px 0 0;padding-left:18px;font-size:.8rem}
    .hidden{display:none}.links{margin-top:9px;display:grid;gap:5px}.links a{color:var(--accent);text-decoration:none;font-size:.83rem;font-weight:620}.links a:hover{text-decoration:underline}
    .log{margin-top:9px;border:1px dashed #c0cedf;border-radius:9px;padding:9px;background:#f8fbff;max-height:360px;overflow:auto;font-size:.77rem;font-family:"IBM Plex Mono","Consolas",monospace;white-space:pre-wrap}
    @media (max-width:1040px){.layout{grid-template-columns:1fr}.side{position:static}} @media (max-width:860px){.g3{grid-template-columns:repeat(2,minmax(0,1fr))}} @media (max-width:620px){.g3,.g2{grid-template-columns:1fr}.btn{width:100%}.pair-row{grid-template-columns:1fr}}
  </style>
</head>
<body>
<main class="page">
  <h1 class="title">ShearTors RC - Crear y ejecutar job</h1>
  <p class="subtitle">Genera el caso desde formulario y ejecuta el flujo ETABS sin editar manualmente el <code>case.json</code>.</p>
  <div class="layout">
    <form id="job-form" novalidate>
      <section class="card"><h2 class="h2">Informacion general</h2><p class="note">Parametros base del caso y configuracion de diseno.</p><div class="grid g3"><div class="field"><label for="api_key">API Key (opcional)</label><input id="api_key" name="api_key" autocomplete="off" placeholder="Solo si APP_API_KEY esta activa" /></div><div class="field"><label for="case_name">Nombre del caso</label><input id="case_name" name="case_name" value="case_web" /></div><div class="field"><label for="beam_id">Beam ID</label><input id="beam_id" name="beam_id" value="B1" /></div><div class="field"><label for="sheet_name">Hoja ETABS</label><input id="sheet_name" name="sheet_name" value="Conc Bm Sum - ACI 318-08" /><p class="help">Debe coincidir exactamente en ambos Excel.</p></div><div class="field"><label for="detailing">Detailing</label><select id="detailing" name="detailing"><option value="DMO" selected>DMO</option><option value="DES">DES</option></select></div><div class="field"><label for="units_rebar_per_length">Unidad VRebar/TTrnRebar</label><select id="units_rebar_per_length" name="units_rebar_per_length"><option value="mm2/m" selected>mm2/m</option><option value="cm2/m">cm2/m</option></select></div></div></section>
      <section class="card"><h2 class="h2">Materiales</h2><div class="grid g2"><div class="field"><label for="fc_mpa">f'c (MPa)</label><input id="fc_mpa" name="fc_mpa" type="number" value="28" step="0.1" /></div><div class="field"><label for="fy_mpa">fy (MPa)</label><input id="fy_mpa" name="fy_mpa" type="number" value="420" step="0.1" /></div></div></section>
      <section class="card"><h2 class="h2">Geometria</h2><div class="grid g3"><div class="field"><label for="width_mm">Ancho de viga (mm)</label><input id="width_mm" name="width_mm" type="number" value="300" step="0.1" /></div><div class="field"><label for="height_mm">Altura de viga (mm)</label><input id="height_mm" name="height_mm" type="number" value="600" step="0.1" /></div><div class="field"><label for="d_mm">Peralte efectivo d (mm)</label><input id="d_mm" name="d_mm" type="number" value="600" step="0.1" /></div><div class="field"><label for="cover_side_mm">Recubrimiento lateral (mm)</label><input id="cover_side_mm" name="cover_side_mm" type="number" value="40" step="0.1" /></div><div class="field"><label for="cover_top_mm">Recubrimiento superior (mm)</label><input id="cover_top_mm" name="cover_top_mm" type="number" value="40" step="0.1" /></div><div class="field"><label for="cover_bottom_mm">Recubrimiento inferior (mm)</label><input id="cover_bottom_mm" name="cover_bottom_mm" type="number" value="40" step="0.1" /></div></div></section>
      <section class="card"><h2 class="h2">Refuerzo base</h2><div class="grid g3"><div class="field"><label for="db_bar">Barra longitudinal de referencia (db_bar)</label><select id="db_bar" name="db_bar"><option>#3</option><option>#4</option><option>#5</option><option selected>#6</option><option>#7</option><option>#8</option></select></div><div class="field"><label for="min_branches_c">Minimo ramas en region C</label><input id="min_branches_c" name="min_branches_c" type="number" value="4" step="1" min="1" /><p class="help">Si TTrnRebar > 0 usa minimo 2 ramas.</p></div><div class="field"><label for="min_branches_nc">Minimo ramas en region NC</label><input id="min_branches_nc" name="min_branches_nc" type="number" value="2" step="1" min="1" /><p class="help">Con TTrnRebar > 0, una sola rama no es valida.</p></div><div class="field"><label for="region_c_ratio">Fraccion C en extremos</label><input id="region_c_ratio" name="region_c_ratio" type="number" value="0.2" step="0.01" /><p class="help">Valor valido entre 0 y 0.5.</p></div></div></section>
      <section class="card"><h2 class="h2">Archivos ETABS</h2><div class="grid g2"><div class="field"><label for="seismic_excel">Excel sismico</label><input id="seismic_excel" name="seismic_excel" type="file" accept=".xlsx" required /></div><div class="field"><label for="gravity_excel">Excel gravedad</label><input id="gravity_excel" name="gravity_excel" type="file" accept=".xlsx" required /></div></div></section>
      <section class="card"><details class="adv"><summary>Configuracion avanzada (opcional)</summary><div class="adv-body"><input type="hidden" id="frame_pairs_json" name="frame_pairs_json" /><input type="hidden" id="optimization_overrides_json" name="optimization_overrides_json" />
        <div class="adv-block"><div class="toggle"><input type="checkbox" id="enable_frame_pairs" /><label for="enable_frame_pairs">Usar mapeo avanzado de vanos</label></div><p class="mini-note">Define pares solo si el vano sismico y el de gravedad no coinciden.</p><div id="frame-pairs-fields" class="adv-disabled"><div id="frame-pairs-list" class="pairs"></div><button type="button" class="mini-btn" id="btn-add-pair">Agregar mapeo</button></div></div>
        <div class="adv-block"><div class="toggle"><input type="checkbox" id="enable_optimization_overrides" /><label for="enable_optimization_overrides">Personalizar optimizacion</label></div><p class="mini-note">La UI genera el JSON que ya espera el backend.</p><div id="optimization-fields" class="grid g2 adv-disabled"><div class="field"><label for="opt_generations">Cantidad de generaciones</label><input id="opt_generations" type="number" min="1" step="1" placeholder="Ej: 80" /><p class="help">Entero >= 1.</p></div><div class="field"><label for="opt_e_bars">Diametros para estribos cerrados</label><input id="opt_e_bars" type="text" placeholder="Ej: #3, #4, #6" /><p class="help">Separados por coma.</p></div><div class="field"><label for="opt_g_bars">Diametros para ramas simples</label><input id="opt_g_bars" type="text" placeholder="Ej: #3, #4, #6" /><p class="help">Separados por coma.</p></div><div class="field"><label for="opt_long_bars">Diametros para refuerzo longitudinal</label><input id="opt_long_bars" type="text" placeholder="Ej: #4, #5, #6" /><p class="help">Separados por coma.</p></div><div class="field"><label for="opt_spacing">Espaciamientos posibles de estribos (mm)</label><input id="opt_spacing" type="text" placeholder="Ej: 70, 80, 100" /><p class="help">Enteros positivos separados por coma.</p></div><div class="field"><label for="opt_long_counts">Cantidades posibles de barras longitudinales</label><input id="opt_long_counts" type="text" placeholder="Ej: 2, 4, 6, 8" /><p class="help">Enteros positivos separados por coma.</p></div></div></div>
      </div></details></section>
      <section class="card"><div class="actions"><button type="submit" class="btn btn-primary" id="btn-submit"><span class="spinner" aria-hidden="true"></span><span id="btn-submit-label">Crear y ejecutar job</span></button><button type="button" class="btn btn-secondary" id="btn-clear">Limpiar estado</button></div></section>
    </form>
    <aside class="card side" id="feedback-panel"><h2 class="h2">Ejecucion y resultados</h2><p class="note">Monitoreo del job, errores del backend y accesos rapidos.</p><div id="status" class="status" aria-live="polite">Esperando ejecucion</div><div id="error-box" class="alert hidden" role="alert" aria-live="assertive"></div><div id="links" class="links"></div><pre id="details" class="log hidden"></pre></aside>
  </div>
</main>
<script>
const form=document.getElementById("job-form"),submitBtn=document.getElementById("btn-submit"),submitLabel=document.getElementById("btn-submit-label"),clearBtn=document.getElementById("btn-clear"),statusEl=document.getElementById("status"),linksEl=document.getElementById("links"),detailsEl=document.getElementById("details"),errorBoxEl=document.getElementById("error-box"),feedbackPanel=document.getElementById("feedback-panel"),hiddenFramePairsInput=document.getElementById("frame_pairs_json"),hiddenOptimizationInput=document.getElementById("optimization_overrides_json"),enableFramePairs=document.getElementById("enable_frame_pairs"),framePairsFields=document.getElementById("frame-pairs-fields"),framePairsList=document.getElementById("frame-pairs-list"),addPairBtn=document.getElementById("btn-add-pair"),enableOptimizationOverrides=document.getElementById("enable_optimization_overrides"),optimizationFields=document.getElementById("optimization-fields"),optGenerations=document.getElementById("opt_generations"),optEBars=document.getElementById("opt_e_bars"),optGBars=document.getElementById("opt_g_bars"),optLongBars=document.getElementById("opt_long_bars"),optSpacing=document.getElementById("opt_spacing"),optLongCounts=document.getElementById("opt_long_counts");
let pollTimer=null,isSubmitting=false,currentJobId=null;
function scrollToFeedback(){feedbackPanel.scrollIntoView({behavior:"smooth",block:"start"})}
function headersWithApiKey(){const key=(document.getElementById("api_key").value||"").trim();return key?{"X-API-Key":key}:{}}
function setStatus(text,tone=""){statusEl.className="status";if(tone)statusEl.classList.add(tone);statusEl.textContent=text}
function stopPolling(){if(pollTimer){clearInterval(pollTimer);pollTimer=null}}
function setSubmitting(flag){isSubmitting=flag;submitBtn.disabled=flag;submitBtn.classList.toggle("is-loading",flag);submitLabel.textContent=flag?"Creando job...":"Crear y ejecutar job"}
function clearErrorBox(){errorBoxEl.classList.add("hidden");errorBoxEl.innerHTML=""}
function clearFieldErrors(){form.querySelectorAll("[aria-invalid='true']").forEach(el=>el.setAttribute("aria-invalid","false"));form.querySelectorAll(".field-error").forEach(el=>el.remove())}
function markElementError(el,msg){if(!el)return;el.setAttribute("aria-invalid","true");const w=el.closest(".field");if(!w)return;const p=document.createElement("p");p.className="field-error";p.textContent=msg;w.appendChild(p)}
function mapBackendField(field){if(!field)return null;const raw=String(field).toLowerCase();const m=[["sheet_name","sheet_name"],["region_c_ratio","region_c_ratio"],["min_branches","min_branches_c"],["fc_mpa","fc_mpa"],["fy_mpa","fy_mpa"],["width_mm","width_mm"],["height_mm","height_mm"],["d_mm","d_mm"],["db_bar","db_bar"],["cover_side_mm","cover_side_mm"],["cover_top_mm","cover_top_mm"],["cover_bottom_mm","cover_bottom_mm"],["frame_pairs","enable_frame_pairs"],["optimization","enable_optimization_overrides"],["seismic_excel","seismic_excel"],["gravity_excel","gravity_excel"]];for(const [t,id] of m){if(raw.includes(t))return id}return null}
function normalizeErrorPayload(payload,status){if(!payload||typeof payload!=="object")return{error:"request_error",message:`No fue posible completar la solicitud (HTTP ${status}).`,details:[]};if(Array.isArray(payload.details))return{error:payload.error||"request_error",message:payload.message||"Error de solicitud",details:payload.details};if(Array.isArray(payload.detail))return{error:"validation_error",message:`No fue posible completar la solicitud (HTTP ${status}).`,details:payload.detail.map(it=>({code:it.type||"validation_error",field:Array.isArray(it.loc)?it.loc[it.loc.length-1]:"",message:it.msg||"Entrada invalida",severity:"error"}))};return{error:payload.error||"request_error",message:payload.message||payload.detail||"Error de solicitud",details:[]}}
function renderError(payload){clearErrorBox();clearFieldErrors();const details=Array.isArray(payload?.details)?payload.details:[];const items=[];for(const d of details){const mapped=mapBackendField(d.field||"");if(mapped)markElementError(document.getElementById(mapped),d.message||"Valor no valido");const pref=d.field?`${d.field}: `:"";const suf=d.code?` [${d.code}]`:"";items.push(`<li>${pref}${d.message||"Detalle de validacion"}${suf}</li>`)}const list=items.length?`<ul>${items.join("")}</ul>`:"";errorBoxEl.innerHTML=`<h4>${payload?.message||"Error de solicitud"}</h4><p>Codigo: <strong>${payload?.error||"request_error"}</strong></p>${list}`;errorBoxEl.classList.remove("hidden");setStatus("Se encontraron errores de validacion","err");scrollToFeedback()}
function renderUiValidationErrors(errors){clearErrorBox();const items=[];for(const e of errors){if(e.element)markElementError(e.element,e.message);items.push(`<li>${e.label}: ${e.message}</li>`)}errorBoxEl.innerHTML=`<h4>Revisa la configuracion avanzada</h4><p>Codigo: <strong>ui_validation_error</strong></p><ul>${items.join("")}</ul>`;errorBoxEl.classList.remove("hidden");setStatus("Corrige errores de configuracion avanzada","err");scrollToFeedback()}
function setLinks(jobId,payload){const su=payload.status_url||`/v1/jobs/${jobId}`,du=payload.download_url||`/v1/jobs/${jobId}/download`;linksEl.innerHTML=`<a href="${su}" target="_blank" rel="noreferrer">Ver estado del job</a><a href="${du}" target="_blank" rel="noreferrer">Descargar reportes ZIP</a><a href="/v1/jobs/${jobId}/case" target="_blank" rel="noreferrer">Ver case generado</a>`}
function showStatusPayload(payload){detailsEl.classList.remove("hidden");detailsEl.textContent=JSON.stringify(payload,null,2)}
function createPairRow(initial={}){const row=document.createElement("div");row.className="pair-row";row.innerHTML=`<div class="field"><label>ID del vano</label><input type="text" class="pair-id" placeholder="Ej: S1" /></div><div class="field"><label>Vano sismico</label><input type="text" class="pair-seismic" placeholder="Ej: 190" /></div><div class="field"><label>Vano gravedad</label><input type="text" class="pair-gravity" placeholder="Ej: 190" /></div><div class="field"><label>Accion</label><button type="button" class="mini-btn mini-btn-danger pair-remove">Eliminar</button></div>`;row.querySelector(".pair-id").value=initial.id||"";row.querySelector(".pair-seismic").value=initial.seismic||"";row.querySelector(".pair-gravity").value=initial.gravity||"";row.querySelector(".pair-remove").addEventListener("click",()=>row.remove());return row}
function parseCsvTokens(raw){return String(raw||"").split(",").map(v=>v.trim()).filter(v=>v.length>0)}
function parsePositiveIntList(raw){const t=parseCsvTokens(raw);if(t.length===0)return{ok:false,values:[],message:"La lista no puede estar vacia."};const values=[];for(const token of t){const p=Number(token);if(!Number.isInteger(p)||p<=0)return{ok:false,values:[],message:`Valor invalido: ${token}. Usa enteros positivos.`};values.push(p)}return{ok:true,values,message:""}}
function setAdvancedControlsEnabled(container,en){container.classList.toggle("adv-disabled",!en);container.querySelectorAll("input, button").forEach(el=>{el.disabled=!en})}
function syncAdvancedSections(){setAdvancedControlsEnabled(framePairsFields,enableFramePairs.checked);if(enableFramePairs.checked&&framePairsList.children.length===0)framePairsList.appendChild(createPairRow({}));setAdvancedControlsEnabled(optimizationFields,enableOptimizationOverrides.checked)}
function buildAdvancedPayload(){hiddenFramePairsInput.value="";hiddenOptimizationInput.value="";const errors=[];if(enableFramePairs.checked){const rows=Array.from(framePairsList.querySelectorAll(".pair-row"));if(rows.length===0){errors.push({label:"Mapeo avanzado",element:enableFramePairs,message:"Agrega al menos un mapeo."})}else{const pairs=[];rows.forEach((row,i)=>{const idIn=row.querySelector(".pair-id"),sIn=row.querySelector(".pair-seismic"),gIn=row.querySelector(".pair-gravity"),id=(idIn.value||"").trim()||`S${i+1}`,s=(sIn.value||"").trim(),g=(gIn.value||"").trim();if(!s)errors.push({label:`Mapeo fila ${i+1}`,element:sIn,message:"Vano sismico es obligatorio."});if(!g)errors.push({label:`Mapeo fila ${i+1}`,element:gIn,message:"Vano gravedad es obligatorio."});pairs.push({id,seismic:s,gravity:g})});if(errors.length===0)hiddenFramePairsInput.value=JSON.stringify(pairs)}}if(enableOptimizationOverrides.checked){const genRaw=(optGenerations.value||"").trim(),gen=Number(genRaw);if(!genRaw)errors.push({label:"Generaciones",element:optGenerations,message:"Indica la cantidad de generaciones."});else if(!Number.isInteger(gen)||gen<1)errors.push({label:"Generaciones",element:optGenerations,message:"Debe ser un entero >= 1."});const eb=parseCsvTokens(optEBars.value),gb=parseCsvTokens(optGBars.value),lb=parseCsvTokens(optLongBars.value);if(eb.length===0)errors.push({label:"Estribos cerrados",element:optEBars,message:"Define al menos un diametro."});if(gb.length===0)errors.push({label:"Ramas simples",element:optGBars,message:"Define al menos un diametro."});if(lb.length===0)errors.push({label:"Refuerzo longitudinal",element:optLongBars,message:"Define al menos un diametro."});const sp=parsePositiveIntList(optSpacing.value),lc=parsePositiveIntList(optLongCounts.value);if(!sp.ok)errors.push({label:"Espaciamientos",element:optSpacing,message:sp.message});if(!lc.ok)errors.push({label:"Cantidades longitudinales",element:optLongCounts,message:lc.message});if(errors.length===0)hiddenOptimizationInput.value=JSON.stringify({variables:{E_bars:eb,G_bars:gb,stirrup_spacing_mm:sp.values,longitudinal_bars:lb,longitudinal_bar_counts:lc.values},genetic_algorithm:{generations:gen}})}if(errors.length>0){renderUiValidationErrors(errors);return false}return true}
async function refreshStatus(jobId){const response=await fetch(`/v1/jobs/${jobId}`,{headers:headersWithApiKey()}),payload=await response.json().catch(()=>({}));if(!response.ok){renderError(normalizeErrorPayload(payload,response.status));stopPolling();setSubmitting(false);return}showStatusPayload(payload);if(payload.status==="completed"){setStatus("Job completado. Puedes descargar resultados.","ok");stopPolling();setSubmitting(false);scrollToFeedback();return}if(payload.status==="failed"){renderError({error:"job_failed",message:`El job termino en estado failed${payload.error?`: ${payload.error}`:""}`,details:[]});stopPolling();setSubmitting(false);return}setStatus(`Job en progreso: ${payload.status}`,"running")}
addPairBtn.addEventListener("click",()=>framePairsList.appendChild(createPairRow({})));enableFramePairs.addEventListener("change",syncAdvancedSections);enableOptimizationOverrides.addEventListener("change",syncAdvancedSections);syncAdvancedSections();
form.addEventListener("submit",async(event)=>{event.preventDefault();if(isSubmitting)return;stopPolling();clearErrorBox();clearFieldErrors();detailsEl.classList.add("hidden");detailsEl.textContent="";linksEl.innerHTML="";setSubmitting(true);setStatus("Validando datos y creando job...","running");scrollToFeedback();if(!buildAdvancedPayload()){setSubmitting(false);return}const formData=new FormData(form);if(!formData.get("frame_pairs_json"))formData.delete("frame_pairs_json");if(!formData.get("optimization_overrides_json"))formData.delete("optimization_overrides_json");try{const response=await fetch("/v1/jobs/from-form",{method:"POST",body:formData,headers:headersWithApiKey()}),payload=await response.json().catch(()=>({}));if(!response.ok){renderError(normalizeErrorPayload(payload,response.status));setSubmitting(false);return}currentJobId=payload.job_id;setLinks(currentJobId,payload);setStatus(`Job ${currentJobId} creado. Iniciando monitoreo...`,"running");await refreshStatus(currentJobId);if(!pollTimer&&isSubmitting){pollTimer=setInterval(()=>{refreshStatus(currentJobId).catch((error)=>{renderError({error:"network_error",message:error?.message||"No fue posible consultar el estado del job",details:[]});stopPolling();setSubmitting(false)})},2500)}}catch(error){renderError({error:"network_error",message:error?.message||"No fue posible enviar la solicitud",details:[]});setSubmitting(false)}});
clearBtn.addEventListener("click",()=>{stopPolling();currentJobId=null;setSubmitting(false);setStatus("Esperando ejecucion");linksEl.innerHTML="";detailsEl.textContent="";detailsEl.classList.add("hidden");clearErrorBox();clearFieldErrors()});
</script>
</body>
</html>
"""


@router.get("/ui", response_class=HTMLResponse)
def ui_page() -> HTMLResponse:
    return HTMLResponse(content=UI_HTML)


